---
version: "3"

networks:
  net-speedtest:

volumes:
  grafana_data: {}
  prometheus_data: {}


services:

  #-----------------------------------------------------------------------------
  speedtest-exporter:
    image: fbarmes/speedtest-exporter:1.1-arm
    restart: unless-stopped
    networks:
      - net-speedtest
    ports:
      - 9100:9100

  #-----------------------------------------------------------------------------
  node-exporter:
    image: prom/node-exporter:v1.3.1
    restart: unless-stopped
    networks:
      - net-speedtest
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'

  #-----------------------------------------------------------------------------
  snmp-exporter:
    image: prom/snmp-exporter:v0.20.0
    restart: unless-stopped
    networks:
      - net-speedtest
    ports:
      - 9116:9116

  #-----------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:v2.33.5
    networks:
      - net-speedtest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.enable-admin-api"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/data/prometheus
    ports:
      - 9090:9090


  #-----------------------------------------------------------------------------
  grafana:
    image: grafana/grafana:8.4.3
    networks:
      - net-speedtest
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    volumes:
      - ./grafana/provisionning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    ports:
      # grafana UI port
      - 3000:3000
