---
version: "3"

networks:
  net-speedtest:



services:

  #-----------------------------------------------------------------------------
  speedtest-exporter:
    image: fbarmes/speedtest-exporter:1.1-arm
    restart: unless-stopped
    networks:
      - net-speedtest
    ports:
      - 9100:9100

  #-----------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:v2.33.5
    networks:
      - net-speedtest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.enable-admin-api"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090


  #-----------------------------------------------------------------------------
  grafana:
    image: grafana/grafana:8.4.3
    networks:
      - net-speedtest
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    volumes:
      - ./grafana/provisionning/:/etc/grafana/provisioning/
    ports:
      # grafana UI port
      - 3000:3000
