{
 "title": "snmp",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DC_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(snmp_scrape_duration_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "In traffic by interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ifInOctets{instance=\"$instance\" } > 0",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "OUT traffic by interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ifOutOctets{instance=\"$instance\" } > 0",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "In traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate( ifInOctets{instance=\"$instance\", ifName!~\"CPU.*\" }[5m] ) > 0",
     "legendFormat": "{{ifName}}-in"
    }
   ]
  },
  {
   "title": "Out traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate( ifOutOctets{instance=\"$instance\", ifName!~\"CPU.*\" }[5m] ) > 0",
     "legendFormat": "{{ifName}}-out"
    }
   ]
  },
  {
   "title": "In traffic rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate( ifInOctets{instance=\"$instance\", ifName!~\"CPU.*\" }[5m] ) > 0",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Out traffic rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate( ifOutOctets{instance=\"$instance\", ifName!~\"CPU.*\" }[5m] ) > 0",
     "legendFormat": "{{ifName}}"
    }
   ]
  }
 ]
}