#
# Prometheus configuration file
#
#

#-------------------------------------------------------------------------------
# Global Configuration
#-------------------------------------------------------------------------------
global:
  scrape_interval:     30s
  scrape_timeout:      30s
  evaluation_interval: 30s

#-------------------------------------------------------------------------------
# Scrape configuration
#
#-------------------------------------------------------------------------------

scrape_configs:
  #--------------------------------------------
  # scrape prometheus itself
  #--------------------------------------------
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090
  #--------------------------------------------
  # scrape speedtest
  #--------------------------------------------
  - job_name: speedtest
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - speedtest-exporter:9100

  #--------------------------------------------
  # scrape metrics
  #--------------------------------------------
  - job_name: metrics
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - node-exporter:9100
        - snmp-exporter:9116


  #--------------------------------------------
  # scrape snmp
  #--------------------------------------------
  - job_name: snmp
    honor_timestamps: true
    metrics_path: /snmp
    params:
      module: [if_mib]
    static_configs:
      - targets:
        - 192.168.1.2
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # The SNMP exporter's real hostname:port.
